In [112]:
#why we need feature scaling?
# all the variables may not have same scale we need to do feature scaling
# age extends from 27 to 50 and at the same time salary scales from 48k to 83k
#LOT OF MACHINE LEARNING MODELS ARE BASED ON EUCLIDEAN DISTANCE. 
#Here, salary has wider range than that of age thus salary has more impact than
#age. they both have to be in same range since they have to be on the 
#coordinates on the graph.

In [113]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [114]:
dataset = pd.read_csv("Data.csv")
print(len(dataset))

10


In [115]:
#missing values
print(dataset.iloc[:,1].values)
age_col = dataset.iloc[:, 1].values
print(age_col)
print(dataset.iloc[:,2].values)
sal_col = dataset.iloc[:,2].values
print(sal_col)

[44. 27. 30. 38. 40. 35. nan 48. 50. 37.]
[44. 27. 30. 38. 40. 35. nan 48. 50. 37.]
[72000. 48000. 54000. 61000.    nan 58000. 52000. 79000. 83000. 67000.]
[72000. 48000. 54000. 61000.    nan 58000. 52000. 79000. 83000. 67000.]


In [116]:
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values="NaN", strategy = "mean", axis = 0)
age_col = age_col.reshape(-1 , 1)
age_imputer = imputer.fit(age_col)
age_col = age_imputer.transform(age_col)
age_col = age_col.ravel()
dataset.iloc[:,1] = age_col
print(age_col)
print(dataset)

[44.         27.         30.         38.         40.         35.
 38.77777778 48.         50.         37.        ]
   Country        Age   Salary Purchased
0   France  44.000000  72000.0        No
1    Spain  27.000000  48000.0       Yes
2  Germany  30.000000  54000.0        No
3    Spain  38.000000  61000.0        No
4  Germany  40.000000      NaN       Yes
5   France  35.000000  58000.0       Yes
6    Spain  38.777778  52000.0        No
7   France  48.000000  79000.0       Yes
8  Germany  50.000000  83000.0        No
9   France  37.000000  67000.0       Yes


C:\Users\JEPRSDD\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [117]:
sal_col = sal_col.reshape(-1, 1)
sal_imputer = imputer.fit(sal_col)
sal_col = sal_imputer.transform(sal_col)
sal_col = sal_col.ravel()
dataset.iloc[:,2] = sal_col
print(sal_col)
print(dataset)

[72000.         48000.         54000.         61000.
 63777.77777778 58000.         52000.         79000.
 83000.         67000.        ]
   Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes


In [118]:
#encoding with labelencoder and onehotencoder
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
cou_col = dataset.iloc[:,0].values
cou_col = label_encoder.fit_transform(cou_col)
dataset.iloc[:,0] = cou_col
print(cou_col)
print(dataset)

[0 2 1 2 1 0 2 0 1 0]
   Country        Age        Salary Purchased
0        0  44.000000  72000.000000        No
1        2  27.000000  48000.000000       Yes
2        1  30.000000  54000.000000        No
3        2  38.000000  61000.000000        No
4        1  40.000000  63777.777778       Yes
5        0  35.000000  58000.000000       Yes
6        2  38.777778  52000.000000        No
7        0  48.000000  79000.000000       Yes
8        1  50.000000  83000.000000        No
9        0  37.000000  67000.000000       Yes


In [119]:
#encoding with labelencoder - y
y_col = dataset.iloc[:,-1].values
from sklearn.preprocessing import LabelEncoder
le_y = LabelEncoder()
y_col = le_y.fit_transform(y_col)
dataset.iloc[:,-1] = y_col
print(y_col)
print(dataset)

[0 1 0 0 1 1 0 1 0 1]
   Country        Age        Salary  Purchased
0        0  44.000000  72000.000000          0
1        2  27.000000  48000.000000          1
2        1  30.000000  54000.000000          0
3        2  38.000000  61000.000000          0
4        1  40.000000  63777.777778          1
5        0  35.000000  58000.000000          1
6        2  38.777778  52000.000000          0
7        0  48.000000  79000.000000          1
8        1  50.000000  83000.000000          0
9        0  37.000000  67000.000000          1


In [120]:
#encoding with one hot encoder
from sklearn.preprocessing import OneHotEncoder
ohn = OneHotEncoder(categorical_features = [0])
X = dataset.iloc[:, 0:3].values
print(X)
X = ohn.fit_transform(X).toarray()
print(X)

[[0.00000000e+00 4.40000000e+01 7.20000000e+04]
 [2.00000000e+00 2.70000000e+01 4.80000000e+04]
 [1.00000000e+00 3.00000000e+01 5.40000000e+04]
 [2.00000000e+00 3.80000000e+01 6.10000000e+04]
 [1.00000000e+00 4.00000000e+01 6.37777778e+04]
 [0.00000000e+00 3.50000000e+01 5.80000000e+04]
 [2.00000000e+00 3.87777778e+01 5.20000000e+04]
 [0.00000000e+00 4.80000000e+01 7.90000000e+04]
 [1.00000000e+00 5.00000000e+01 8.30000000e+04]
 [0.00000000e+00 3.70000000e+01 6.70000000e+04]]
[[1.00000000e+00 0.00000000e+00 0.00000000e+00 4.40000000e+01
  7.20000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 2.70000000e+01
  4.80000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 3.00000000e+01
  5.40000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.80000000e+01
  6.10000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 4.00000000e+01
  6.37777778e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.50000000e+01
  5.80000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000

C:\Users\JEPRSDD\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\JEPRSDD\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:385: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [121]:
from sklearn.model_selection import train_test_split
X = dataset.iloc[:,0:3].values
y = dataset.iloc[:, -1].values
print(X)
print(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

[[0.00000000e+00 4.40000000e+01 7.20000000e+04]
 [2.00000000e+00 2.70000000e+01 4.80000000e+04]
 [1.00000000e+00 3.00000000e+01 5.40000000e+04]
 [2.00000000e+00 3.80000000e+01 6.10000000e+04]
 [1.00000000e+00 4.00000000e+01 6.37777778e+04]
 [0.00000000e+00 3.50000000e+01 5.80000000e+04]
 [2.00000000e+00 3.87777778e+01 5.20000000e+04]
 [0.00000000e+00 4.80000000e+01 7.90000000e+04]
 [1.00000000e+00 5.00000000e+01 8.30000000e+04]
 [0.00000000e+00 3.70000000e+01 6.70000000e+04]]
[0 1 0 0 1 1 0 1 0 1]


In [131]:
#feature scaling
from sklearn.preprocessing import StandardScaler
ss_x = StandardScaler()
X_train = ss_x.fit_transform(X_train)
print(X_train)
X_test = ss_x.fit_transform(X_test)
print(X_test)
ss_y = StandardScaler()
y_train = y_train.reshape(-1, 1)
y_train = ss_y.fit_transform(y_train)
print(y_train)

[[ 0.13483997  0.26306757  0.12381479]
 [-0.94387981 -0.25350148  0.46175632]
 [ 1.21355975 -1.97539832 -1.53093341]
 [ 1.21355975  0.05261351 -1.11141978]
 [-0.94387981  1.64058505  1.7202972 ]
 [ 1.21355975 -0.0813118  -0.16751412]
 [-0.94387981  0.95182631  0.98614835]
 [-0.94387981 -0.59788085 -0.48214934]]
[[ 0. -1. -1.]
 [ 0.  1.  1.]]
[[ 0.77459667]
 [ 0.77459667]
 [ 0.77459667]
 [-1.29099445]
 [ 0.77459667]
 [-1.29099445]
 [-1.29099445]
 [ 0.77459667]]
